---
title: "Untitled"
author: "Jason"
date: "12/23/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#				RESTRUCTURING MOOD DATA
```{r Moodsubset, eval=TRUE, echo=FALSE, message=FALSE, comment = ""}

dat2 <- dat1 %>% dplyr::select("ID", "group.factor",
							   "v1.mood", "v2.mood",
							   "visit1moodpre", "visit1moodpost",
							   # contains("mood")
							   "visit2moodpre", "visit2moodpost",
							   )

view(dat2)

############			v1 POSITIVE PRE POST	 ##########
v1pos_dat <- dat2 #filter(dat2, dat2$visit1moodpre != "NA")
#view(v1pos_dat)

v1pos_dat <- v1pos_dat %>% 
	dplyr::select("ID", "group.factor", "v1.mood",
				  contains("visit1")) %>% 
	filter(v1.mood == "pos")

names(v1pos_dat)[names(v1pos_dat) == 'visit1moodpre'] <- 'pos_pre'
names(v1pos_dat)[names(v1pos_dat) == 'visit1moodpost'] <- 'pos_post'
names(v1pos_dat)[names(v1pos_dat) == 'v1.mood'] <- 'mood'

v1pos_dat <- as_tibble(v1pos_dat)
head(v1pos_dat)

#view(v1pos_dat)

############			v1 NEGATIVE PRE POST	 ##########

v1neg_dat <- dat2 #filter(dat2, dat2$visit1moodpre != "NA")
#view(v1neg_dat)

v1neg_dat <- v1neg_dat %>% 
	dplyr::select("ID", "group.factor", "v1.mood",
				  contains("visit1")) %>% 
	filter(v1.mood == "neg")

names(v1neg_dat)[names(v1neg_dat) == 'visit1moodpre'] <- 'neg_pre'
names(v1neg_dat)[names(v1neg_dat) == 'visit1moodpost'] <- 'neg_post'
names(v1neg_dat)[names(v1neg_dat) == 'v1.mood'] <- 'mood'

v1neg_dat <- as_tibble(v1neg_dat)
head(v1neg_dat)

#view(v1neg_dat)


############			v2 POSITIVE PRE POST	 ##########
v2pos_dat <- dat2 #filter(dat2, dat2$visit2moodpre != "NA")
#view(v2pos_dat)

v2pos_dat <- v2pos_dat %>% 
	dplyr::select("ID", "group.factor", "v2.mood",
				  contains("visit2")) %>% 
	filter(v2.mood == "pos")

names(v2pos_dat)[names(v2pos_dat) == 'visit2moodpre'] <- 'pos_pre'
names(v2pos_dat)[names(v2pos_dat) == 'visit2moodpost'] <- 'pos_post'
names(v2pos_dat)[names(v2pos_dat) == 'v2.mood'] <- 'mood'


v2pos_dat <- as_tibble(v2pos_dat)
head(v2pos_dat)

#view(v2pos_dat)

############			v2 NEGATIVE PRE POST	 ##########

v2neg_dat <- dat2 #filter(dat2, dat2$visit2moodpre != "NA")
#view(v2neg_dat)

v2neg_dat <- v2neg_dat %>% 
	dplyr::select("ID", "group.factor", "v2.mood",
				  contains("visit2")) %>% 
	filter(v2.mood == "neg")

names(v2neg_dat)[names(v2neg_dat) == 'visit2moodpre'] <- 'neg_pre'
names(v2neg_dat)[names(v2neg_dat) == 'visit2moodpost'] <- 'neg_post'
names(v2neg_dat)[names(v2neg_dat) == 'v2.mood'] <- 'mood'

v2neg_dat <- as_tibble(v2neg_dat)
head(v2neg_dat)

#view(v2neg_dat)

###########				JOINING			####

pos_dat <- full_join(v1pos_dat, v2pos_dat)
#view(pos_dat)

neg_dat <- full_join(v1neg_dat, v2neg_dat)
#view(neg_dat)

neg_dat2 <- neg_dat %>% dplyr::select("ID", "neg_pre", "neg_post")
#view(neg_dat2)

full_dat <- dat2 %>% dplyr::select("ID", "group.factor")
#view(full_dat)

full_dat <- left_join(full_dat, pos_dat)
#view(full_dat)

full_dat <- full_join(full_dat, neg_dat2)
#view(full_dat)

full_dat <- full_dat %>% dplyr::select(-mood)
names(full_dat)[names(full_dat) == 'group.factor'] <- 'group'
#view(full_dat)

######				COMPUTE CHANGE SCORES				######
full_dat <- mutate(full_dat,
				   pos_chng = pos_post - pos_pre,
				   neg_chng = neg_post - neg_pre
				   )

full_dat <- arrange(full_dat, group) %>% 
	filter(group != "NA")


#view(full_dat)

```

#				T-TESTS
```{r , eval=FALSE, echo=FALSE, message=FALSE, comment = ""}

###########				T-TESTS: GROUP BY 4 CONDITIONS		#########
attach(full_dat)
t.test(pos_pre ~ group, mu=0, alt="two.sided", conf=0.95, var.eq=F, paired=F)
t.test(pos_post ~ group, mu=0, alt="two.sided", conf=0.95, var.eq=F, paired=F)
t.test(neg_pre ~ group, mu=0, alt="two.sided", conf=0.95, var.eq=F, paired=F)
t.test(neg_post ~ group, mu=0, alt="two.sided", conf=0.95, var.eq=F, paired=F)


t.test(pos_pre, neg_pre)
t.test(pos_post, neg_post)


```


#		ANOVA - mood
```{r MoodANOVA, eval=TRUE, echo=FALSE, message=FALSE, comment = ""}
########			ANOVA OF MOOD VARIABLES		######

#view(full_dat)
head(full_dat)

#		VARIABLES FOR ANOVA
#		1.	group
#		2.	pos_pre
#		3.	pos_post
#		4.	neg_pre
#		5.	neg_post
#		6.	pos_chng
#		7. neg_chng
#	

# Box plots
# ++++++++++++++++++++
# Plot weight by group and color by group

ggboxplot(full_dat, x = "group", y = "neg_chng", 
          color = "group", palette = c("#00AFBB", "#E7B800", "#FC4E07"),
          order = c("HC", "CLBP", "FM"),
          ylab = "Neg mood change", xlab = "Group")

######			Compute the analysis of variance		######
Pospre_aov <- aov(pos_pre ~ group, data = full_dat)
# Summary of the analysis
summary(Pospre_aov)


# construct anova model for each column of dat1[, my_outcome_variables]
model_summaries <- full_dat[,c("pos_pre", "pos_post",
							   "neg_pre", "neg_post",
							   "pos_chng", "neg_chng"
							   )] %>%
	purrr::map(~ aov(.x ~ group, data = full_dat))  %>%
	# append the TukeyHSD CI estimates
	purrr::map(function(x) {
		list(
			model = x,
			tukey = TukeyHSD(x)
		)
	})

####		THIS RETURNS THE RESULTS OF THE OVERALL ANOVA	####
GetModels <- function(l) l$model
Models <- purrr::map(model_summaries, GetModels) %>% 
  purrr::map_dfr(broom::tidy, .id = "Name")
# head(Models)

#		
Models2 <- filter(Models,  term !="Residuals")
Models2 <- Models2 %>% 
	dplyr::select("Name" , "p.value")


###			ANOVA TABLE MADE WITH KABLE			####
library(kableExtra)
Models2 %>%
	mutate(p.value = 
		   	cell_spec(
		   		(formatC(x = p.value, 
		   				 digits=3, width = 3, 
		   				 format='g', flag = "-", drop0trailing = TRUE, 
		   				 preserve.width = "common")), "html",
		   		color = ifelse(p.value <= 0.054, 
		   					   yes="red", no="blue"), escape = F)
	) %>% 
	mutate_if(is.numeric, function(x) {
		cell_spec(
			(formatC(x,digits=3, width=3, 
					 format="f", flag="-", drop0trailing = FALSE)),
			"html")}
	) %>%
	kable("html", escape = FALSE, align = "l", padding = 4,
		  caption = "ANOVA full model") %>%
	kable_styling(c("striped", "bordered", "hover"), full_width = F) %>%
	footnote(general = "Red = Significant main effect for group (p ≤ 0.05)")  %>% 
	row_spec(0, bold = T, color = "white", background = "#461B7E" )

##		END		##


```


## POSTHOC 
```{r PostHoc-Scaled, eval=TRUE, echo=FALSE, message=FALSE}
######			POST-HOC ANALYSES OF MOOD VARIABLES			######
GetTukeys <- function(m) m$tukey
Tukeys  <- purrr::map(model_summaries, GetTukeys)  %>% 
	purrr::map_dfr(broom::tidy, .id = "Name")
 # head(Tukeys)
#view(Tukeys)

names(Tukeys)[names(Tukeys) == 'Name'] <- 'Var'
names(Tukeys)[names(Tukeys) == 'estimate'] <- 'diff'



######			POST-HOC TABLE USING KABLE			######
select(Tukeys, -term, -Var) %>%
	mutate(adj.p.value = 
		   	cell_spec((formatC(x = adj.p.value, 
		   					   digits=3, width = 3, 
		   					   format='g', flag = "-", drop0trailing = TRUE, 
		   					   preserve.width = "common")), "html",
		   			  color = ifelse(adj.p.value <= 0.054, 
		   			  			   yes="red", no="blue"), escape = F)) %>% 
	mutate_if(is.numeric, function(x) {
		cell_spec((formatC(x,digits=3, width=3, 
						   format="f", flag="-", drop0trailing = FALSE)),
				  "html")}) %>%
	kable("html", escape = FALSE, align = "l", 
		  caption = "PostHoc group comparisons: **See** *Note* at table end",
		  padding = 2) %>%
	kable_styling(c("striped", "bordered", "hover"), full_width = F) %>%
	footnote(general = "Red = Significant group tests (p ≤ 0.05)")  %>% 
	row_spec(0, bold = T, color = "white", background = "#461B7E" ) %>% 
	pack_rows(index = c(" " = 0, 
						"pos_pre" = 3,
						"pos_post" = 3,
						"neg_pre" = 3,
						"neg_post" = 3,
						"pos_chng" = 3,
						"neg_chng" = 3
						))
# scroll_box(height = "500px")


```


#		ANOVAS
## 		ANOVA Behavior (Main effect of group)
```{r ANOVA-scaleddata, eval=TRUE, echo=FALSE, message=FALSE}
# construct anova model for each column of dat1[, my_outcome_variables]
model_summaries2 <- dat1[,c("slpQual", "slpLat", "slpDur",
						   "slpEff", "slpDist","slpMeds",
						   "slpDayFcn", "psqi_Global","ess_total",
						   "isi_total", "bdi_total", "mcgill_total",
						   "TIB")] %>%
  purrr::map(~ aov(.x ~ group.factor, data = dat1))  %>%
  # append the TukeyHSD CI estimates
  purrr::map(function(x) {
    list(
      model = x,
      tukey = TukeyHSD(x)
    )
  })

####		THIS RETURNS THE RESULTS OF THE OVERALL ANOVA	####
GetModels <- function(l) l$model
Models3 <- purrr::map(model_summaries2, GetModels) %>% 
  purrr::map_dfr(broom::tidy, .id = "Name")
# head(Models)

#		
Models3 <- filter(Models3,  term !="Residuals")
Models3 <- Models2 %>% 
	dplyr::select("Name" , "p.value")


####			ANOVA TABLE MADE WITH KABLE			####
Models3 %>%
	mutate(p.value = 
		   	cell_spec(
		   		(formatC(x = p.value, 
		   				 digits=3, width = 3, 
		   				 format='g', flag = "-", drop0trailing = TRUE, 
		   				 preserve.width = "common")), "html",
		   		color = ifelse(p.value <= 0.054, 
		   					   yes="red", no="blue"), escape = F)
	) %>% 
	mutate_if(is.numeric, function(x) {
		cell_spec(
			(formatC(x,digits=3, width=3, 
					 format="f", flag="-", drop0trailing = FALSE)),
			"html")}
	) %>%
	kable("html", escape = FALSE, align = "l", padding = 4,
		  caption = "ANOVA full model") %>%
	kable_styling(c("striped", "bordered", "hover"), full_width = F) %>%
	footnote(general = "Red = Significant main effect for group (p ≤ 0.05)")  %>% 
	row_spec(0, bold = T, color = "white", background = "#461B7E" )

##		END		##
```


ANOVA procedure found on the web
## ANOVA - web
```{r ANOVAmethod2, eval=TRUE, echo=FALSE, message=FALSE, comment = ""}


dat <- dat1[,c("slpQual", "slpLat", "slpDur",
				"slpEff", "slpDist","slpMeds",
				"slpDayFcn", "psqi_Global","ess_total",
				"bdi_total", "mcgill_total",
				"TIB", "group.factor")]  %>% 
	filter("psqi_Global" != "NA") %>% 
	filter("mcgill_total" != "NA") %>% 
	filter("bdi_total" != "NA")
	
zdat <- dat %>% filter(group.factor != "NA")
zdat <- dat %>% filter(group.factor != "FM")
zdat <- zdat %>% filter(psqi_Global != "NA")
zdat <- zdat %>% filter(mcgill_total != "NA")
zdat <- zdat %>% filter(bdi_total != "NA")
	



dat <- zdat

# dat <- iris

# Edit from here
x <- which(names(dat) == "group.factor") # name of grouping variable
y <- which(names(dat) == "bdi_total" # names of variables to test
| names(dat) == "psqi_Global"
| names(dat) == "mcgill_total")
# | names(dat) == "slpQual"
# | names(dat) == "slpLat"
# | names(dat) == "slpDur"
# | names(dat) == "isi_total"
method1 <- "anova" # one of "anova" or "kruskal.test"
method2 <- "t.test" # one of "wilcox.test" or "t.test"
#my_comparisons <- list(c("HC", "CLBP"), c("HC", "FM"), c("CLBP", "FM")) # comparisons for post-hoc tests
my_comparisons <- list(c("HC", "CLBP"))#, c("HC", "CLBP"))#, c("CLBP", "HC")) # comparisons for post-hoc tests
# Edit until here


# Edit at your own risk
for (i in y) {
  for (j in x) {
    p <- ggboxplot(dat,
      x = colnames(dat[j]), y = colnames(dat[i]),
      color = colnames(dat[j]),
      legend = "none",
      palette = "npg",
      add = "jitter"
    )
    print(
      p + stat_compare_means(aes(label = paste0(..method.., ", p-value = ", ..p.format.., " (", ifelse(..p.adj.. > 0.05, "not significant", ..p.signif..), ")")),
        method = method1, label.y = max(dat[, i], na.rm = TRUE)
      )
      + stat_compare_means(comparisons = my_comparisons, method = method2, label = "p.format") # remove if p-value of ANOVA or Kruskal-Wallis test >= 0.05
    )
  }
}

```
